version: '3.8'
services:
  app:
    container_name: coding-test-be
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - 3030:3030
    restart: on-failure
    volumes:
      - api:/usr/src/app/

volumes:
  api:
  database_postgres:
